### ISSUE TITLE
Can't compile with php-5.4.38

### ISSUE THREAD

**Issue by mtrofimm** [commandprompt/PL-php#4]
I installed php-5.4.38 from source:
./configure --enable-embed --prefix=/usr/local && make install

and then try to compie PL-PHP:
 ./configure -with-php=/usr/local/ 
[here everything is OK]

$ make

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -
pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -I/usr/local/include/php -I/usr/local
/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4
/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o plphp.o plphp.c
plphp.c:361:2: warning: initialization left-hand side might be a candidate for a format attribute [-Wsuggest-attribute=format]
  php_error,     /\* sapi_error(int, const char _, ...) */
  ^
In file included from /usr/local/include/php/main/fopen_wrappers.h:25:0,
                 from /usr/local/include/php/main/php.h:398,
                 from plphp.c:83:
plphp.c: In function ‘plphp_call_handler’:
/usr/local/include/php/main/php_globals.h:32:29: error: ‘struct _php_core_globals’ has no member named ‘safe_mode’
 # define PG(v) (core_globals.v)
                             ^
plphp.c:569:5: note: in expansion of macro ‘PG’
     PG(safe_mode) = desc->trusted;
     ^
/usr/local/include/php/main/php_globals.h:32:29: error: ‘struct _php_core_globals’ has no member named ‘safe_mode’
 # define PG(v) (core_globals.v)
                             ^
plphp.c:578:5: note: in expansion of macro ‘PG’
     PG(safe_mode) = desc->trusted;
     ^
plphp.c: In function ‘plphp_validator’:
plphp.c:648:3: warning: implicit declaration of function ‘GETSTRUCT’ [-Wimplicit-function-declaration]
   procForm = (Form_pg_proc) GETSTRUCT(procTup);
   ^
plphp.c:648:14: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   procForm = (Form_pg_proc) GETSTRUCT(procTup);
              ^
plphp.c: In function ‘plphp_func_handler’:
plphp.c:1006:19: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   retTypeStruct = (Form_pg_type) GETSTRUCT(retTypeTup);
                   ^
plphp.c: In function ‘plphp_compile_function’:
plphp.c:1195:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  procStruct = (Form_pg_proc) GETSTRUCT(procTup);
               ^
plphp.c:1223:4: warning: implicit declaration of function ‘HeapTupleHeaderGetXmin’ [-Wimplicit-function-declaration](prodesc->fn_xmin == HeapTupleHeaderGetXmin%28procTup->t_data%29 &&
    ^
plphp.c:1224:5: warning: implicit declaration of function ‘HeapTupleHeaderGetRawCommandId’ [-Wimplicit-function-declaration]
     prodesc->fn_cmin == HeapTupleHeaderGetRawCommandId%28procTup->t_data%29);
     ^
plphp.c:1312:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   langStruct = (Form_pg_language) GETSTRUCT(langTup);
                ^
plphp.c: In function ‘plphp_func_build_args’:
plphp.c:1634:17: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    typeStruct = (Form_pg_type) GETSTRUCT(typeTup);
                 ^
plphp.c:1657:5: warning: implicit declaration of function ‘HeapTupleHeaderGetDatumLength’ [-Wimplicit-function-declaration]
     tmptup.t_len = HeapTupleHeaderGetDatumLength(td);
     ^
plphp.c:1661:5: warning: implicit declaration of function ‘HeapTupleHeaderGetTypeId’ [-Wimplicit-function-declaration]
     tupType = HeapTupleHeaderGetTypeId(tmptup.t_data);
     ^
plphp.c:1662:5: warning: implicit declaration of function ‘HeapTupleHeaderGetTypMod’ [-Wimplicit-function-declaration]
     tupTypmod = HeapTupleHeaderGetTypMod(tmptup.t_data);
     ^
make: *_\* [plphp.o] Error 1

**Comment by mtrofimm** [comment]
It seems that this field was removed from PHP in 2010:
https://github.com/php/php-src/commit/dd8e59da8f5aafd9d77a0f1f17e5e272d09f643f

**Comment by ironiridis** [comment]
Duplicate of issue #2.
